language: java
jdk:
- oraclejdk8
deploy:
  api_key:
    secure: VbBhyfxmNZuXjvSZyMlZhVH+5O9CnlMNW7IJnYDKiQzHMZDkoVQOtiyogsn66jqRM67d4Jw65Z9UjOHwTvOJYsAWHjaWKxJOL/dJD7QwyiFPibRoOxCTVbC0qyAvegg9vwPMNgBKDlvfqFrnXWSFxFkaRT5NQ13Grx8nr6WyilLdHReubRrg/7D+9e1a9tWYgjPfZXMnb4N5mqz+QdHbVst1OLXW8szMI/J/UWY522ZqG63yzyc1TBt4uHErPd7rLpZFCPui/JJCQz0BIR9X0LDncQ9bKb71r/Lsy7pKrtcDe8Mt0VAE1Lz7XklkZ5htb3HW/GU2yOhuylxRrB44k82SMZNwbXWCihLN7ubSjBkxDUHNLl9kNvm5PUxuFMmLk9ddNyBfncpRaQu7jZCxD1Ap8vzWSaYbn8dd3LqgvRKOxDg6p7MmHOG4q0Mr1X4Ray8DqbXN9glfhAfrsVB8ga+QD6VXEQw9XUx1gQGA51OlB0Cg4xfKKDKvBKbRL2dRZOmVZ/zX4NJpIyWpv6Msg6YQxGNk/4GwjeUXm8JT5KGm4O75uvGvTU55PS3gfd222T9bJ3BogmNxXpZ4H3SXwJoXlkdvWtl7wOiLYAhhqsCRtrNrEeTyL1Cp+AJ4w2xmUdZoY71VuiIJMTUAYfTT91Go9RvXgehjlKrP9uCy0z8=
app: zp-test